### ISSUE TITLE
Producing Project XML files

### ISSUE THREAD

**Issue by banderson1618** [Riverscapes/grain-size-tool#4]
As of this morning, the code now creates an XML file for the project. However, these XML files are just a rough draft, based on guesswork and intuition. Making them more standardized and compliant with other project's XMLs should be the goal with them.

@joewheaton and @wally-mac, can you comment on the improvements we need to see with the auto-generated XML files? The zip file attached contains an example of the output XML file.

[project.rs.zip](https://github.com/Riverscapes/grain-size-tool/files/1992940/project.rs.zip)

**Comment by wally-mac** [comment]
This looks like a great start to me but I'm unfortunately not the XML expert.  @joewheaton can you please chime in?

**Comment by MattReimer** [comment]
Wow. been a while since I saw one of these. It looks 90% great. 

I just validated it and I have a couple of suggestions:

### Name

The spec needs a `<Name>` tag at the top like:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XSD/V1/Project.xsd">
	<Name>My awesome Grainsize Project</Name>
	<ProjectType>GrainSize</ProjectType>
	<MetaData>

... and then later

	<Realizations>
		<GrainSize id="grainsize" dateCreated="2018-05-10T12:40:20.244000" guid="140D9531-16A0-4D12-85F3-6489383D4730" productVersion="0.0.1">
            <Name>some realization name</Name>
			<Inputs>

```

If you just want to make up a string like "GrainSize Project" and "Realization1" that's fine but these tags will ideally get used to populate the tree viewer so the more specific you can make them the better.

### Inputs

I'm not sure exactly what your tool takes but if your inputs are singular there's no need to wrap them in plural tags (Like `<DEM>` inside `<DEMs>`

so this would be fine:

``` xml
	<Inputs>
                <DEM>
                    <Name>NED_DEM_10m_17060103.tif</Name>
                    <Path>01_Inputs\01_DEM\NED_DEM_10m_17060103.tif</Path>
                </DEM>
                <StreamNetwork>
                    <Name>NHD_24K_17060103_Perennial.shp</Name>
                    <Path>01_Inputs\02_StreamNetwork\NHD_24K_17060103_Perennial.shp</Path>
                </StreamNetwork>
                <Precipitation>
                    <Name>wa_id_or_precip.shp</Name>
                    <Path>01_Inputs\03_Precipitation\wa_id_or_precip.shp</Path>
                </Precipitation>
                <OtherValues>
                    <Name>OtherValues.txt</Name>
                    <Path>01_Inputs\04_OtherValues\OtherValues.txt</Path>
                </OtherValues>
	</Inputs>
```

### Analyses

You could probably stand to lose a layer of nesting here unless the `<Model>` tag has some sort of meaning I don't know about:

so like:

``` xml
	<Analyses>
		<Analysis>
		    <Name>Output_1</Name>
                    <Outputs>
                        <StreamNetwork>
                            <Name>GrainSize.lyr</Name>
                            <Path>02_Analyses\Output_1\GrainSize.lyr</Path>
                        </StreamNetwork>
                    </Outputs>
		</Analysis>
	</Analyses>
```

Just my `$0.02CAD`. Let me know if you have any questions.

**Comment by banderson1618** [comment]
Thanks for the feedback, @MattReimer, it's appreciated.

If multiple runs are done with different inputs on the same watershed, the tool will put all DEMs in the DEM folder, all stream networks in the Stream Network folder, etc. Making that organization clear was my intent with how they're nested currently. It's redundant in this case, because we only did one run, but I figured I'd prepare for that edge case. I don't have strong feelings on it though, so if you don't think that's worth bothering about, I'm happy to change it.

I'll implement the other changes you mentioned, and post the new and improved file when it's done. Thanks!

**Comment by banderson1618** [comment]
Here's the updated XML file. Let me know if any other issues come up, or whether we should get rid of the nested inputs.

[project.rs.zip](https://github.com/Riverscapes/grain-size-tool/files/1993369/project.rs.zip)

**Comment by MattReimer** [comment]
Almost. 

The Name tag has to go inside the Grainsize tag. 

Also I'm wondering if you saw my note about nesting inputs 

Here's the complete file I'm suggesting:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/Riverscapes/Program/master/Project/XSD/V1/Project.xsd">
    <Name>GrainSizeProject</Name>
    <ProjectType>GrainSize</ProjectType>
    <MetaData>
        <Meta name="CreatedOn">2018-05-10T15:56:06.734000</Meta>
    </MetaData>
    <Realizations>
        <GrainSize id="" dateCreated="2018-05-10T15:56:06.734000" guid="DD5B05CE-E5B5-4AF1-A541-11B4F8CA3727" productVersion="0.0.1">

             <!-- NOTICE: inside the Grainsize tag -->
            <Name>GrainSizeRealization</Name>


            <Inputs>

               <!-- NOTICE: These don't have parents (and shouldn't unless you expect more than one of each type -->

                <DEM>
                    <Name>NED_DEM_10m_17060103.tif</Name>
                    <Path>01_Inputs\01_DEM\NED_DEM_10m_17060103.tif</Path>
                </DEM>
                <StreamNetwork>
                    <Name>NHD_24K_17060103_Perennial.shp</Name>
                    <Path>01_Inputs\02_StreamNetwork\NHD_24K_17060103_Perennial.shp</Path>
                </StreamNetwork>
                <Precipitation>
                    <Name>wa_id_or_precip.shp</Name>
                    <Path>01_Inputs\03_Precipitation\wa_id_or_precip.shp</Path>
                </Precipitation>
                <OtherValues>
                    <Name>OtherValues.txt</Name>
                    <Path>01_Inputs\04_OtherValues\OtherValues.txt</Path>
                </OtherValues>


            </Inputs>
            <Analyses>
                <Analysis>
                    <Name>Output_1</Name>
                    <Outputs>
                        <StreamNetwork>
                            <Name>GrainSize.lyr</Name>
                            <Path>02_Analyses\Output_1\GrainSize.lyr</Path>
                        </StreamNetwork>
                    </Outputs>
                </Analysis>
            </Analyses>
        </GrainSize>
    </Realizations>
</Project>

```

**Comment by banderson1618** [comment]
I saw your comments on inputs, and addressed it in the first comment I made here. Sorry if I didn't make it clear that I was talking about inputs in that post, probably my bad. Regardless, I decided the best solution would be to have each input file without parents if there was only one input, and to keep the parents if there were multiple input files for each type.

I moved the name to the correct spot. Right now, it looks identical to the file that you just posted. I'll attach it anyways, in case you want to check it. Thanks for your help!
[project.rs.zip](https://github.com/Riverscapes/grain-size-tool/files/1993492/project.rs.zip)

**Comment by MattReimer** [comment]
Looks great. Sorry for not seeing that comment. It's what I get when I drink less than ☕️ ☕️ ☕️ ☕️ 

I've added GrainSize to the XSD and pushed it to master so the XML should validate now:

https://github.com/Riverscapes/Program/commit/b8722231d22a7f8c21641ae23d0b8dcc0ed4c592

**Comment by joewheaton** [comment]
This is looking good @banderson1618. Thanks so much @MattReimer for help!
